server:
  port: 8080
  servlet:
    context-path: /eventapp-service

spring:
  application:
    name: eventapp
  jpa:
    show-sql: true
  main:
    banner-mode: off
  datasource:
#    username: root
#    password: Anhtuan@040403
    password: hung0509
    url: jdbc:mysql://localhost:3306/db_eventapp
    username: hung0509
  mail:
    host: smtp.gmail.com
    port: 587
    username: hungtaithe12@gmail.com
    password: hopkkewtcbxocxma
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  secretKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 36000 #seconds

aws:
  access_key: "AKIA2CUNLPLGAA4ZSGCT"
  secret-key: "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"
  bucket: "appeventbucker"
  folder: "image"
  region: "ap-southeast-2"

